/**
 * ISO 4217 currency entries with flag emojis.
 * Bundled statically — no API call, tree-shaken in production.
 */

export interface CurrencyEntry {
	code: string; // ISO 4217 e.g. "PKR"
	name: string; // "Pakistani Rupee"
	country: string; // "Pakistan"
	flag: string; // "🇵🇰"
}

export const CURRENCIES: CurrencyEntry[] = [
	{ code: "AED", name: "UAE Dirham", country: "United Arab Emirates", flag: "🇦🇪" },
	{ code: "AFN", name: "Afghan Afghani", country: "Afghanistan", flag: "🇦🇫" },
	{ code: "ALL", name: "Albanian Lek", country: "Albania", flag: "🇦🇱" },
	{ code: "AMD", name: "Armenian Dram", country: "Armenia", flag: "🇦🇲" },
	{ code: "ANG", name: "Netherlands Antillean Guilder", country: "Netherlands Antilles", flag: "🇳🇱" },
	{ code: "AOA", name: "Angolan Kwanza", country: "Angola", flag: "🇦🇴" },
	{ code: "ARS", name: "Argentine Peso", country: "Argentina", flag: "🇦🇷" },
	{ code: "AUD", name: "Australian Dollar", country: "Australia", flag: "🇦🇺" },
	{ code: "AWG", name: "Aruban Florin", country: "Aruba", flag: "🇦🇼" },
	{ code: "AZN", name: "Azerbaijani Manat", country: "Azerbaijan", flag: "🇦🇿" },
	{ code: "BAM", name: "Bosnia-Herzegovina Convertible Mark", country: "Bosnia and Herzegovina", flag: "🇧🇦" },
	{ code: "BBD", name: "Barbadian Dollar", country: "Barbados", flag: "🇧🇧" },
	{ code: "BDT", name: "Bangladeshi Taka", country: "Bangladesh", flag: "🇧🇩" },
	{ code: "BGN", name: "Bulgarian Lev", country: "Bulgaria", flag: "🇧🇬" },
	{ code: "BHD", name: "Bahraini Dinar", country: "Bahrain", flag: "🇧🇭" },
	{ code: "BIF", name: "Burundian Franc", country: "Burundi", flag: "🇧🇮" },
	{ code: "BMD", name: "Bermudian Dollar", country: "Bermuda", flag: "🇧🇲" },
	{ code: "BND", name: "Brunei Dollar", country: "Brunei", flag: "🇧🇳" },
	{ code: "BOB", name: "Bolivian Boliviano", country: "Bolivia", flag: "🇧🇴" },
	{ code: "BRL", name: "Brazilian Real", country: "Brazil", flag: "🇧🇷" },
	{ code: "BSD", name: "Bahamian Dollar", country: "Bahamas", flag: "🇧🇸" },
	{ code: "BTN", name: "Bhutanese Ngultrum", country: "Bhutan", flag: "🇧🇹" },
	{ code: "BWP", name: "Botswana Pula", country: "Botswana", flag: "🇧🇼" },
	{ code: "BYN", name: "Belarusian Ruble", country: "Belarus", flag: "🇧🇾" },
	{ code: "BZD", name: "Belize Dollar", country: "Belize", flag: "🇧🇿" },
	{ code: "CAD", name: "Canadian Dollar", country: "Canada", flag: "🇨🇦" },
	{ code: "CDF", name: "Congolese Franc", country: "Congo", flag: "🇨🇩" },
	{ code: "CHF", name: "Swiss Franc", country: "Switzerland", flag: "🇨🇭" },
	{ code: "CLP", name: "Chilean Peso", country: "Chile", flag: "🇨🇱" },
	{ code: "CNY", name: "Chinese Yuan", country: "China", flag: "🇨🇳" },
	{ code: "COP", name: "Colombian Peso", country: "Colombia", flag: "🇨🇴" },
	{ code: "CRC", name: "Costa Rican Colón", country: "Costa Rica", flag: "🇨🇷" },
	{ code: "CUP", name: "Cuban Peso", country: "Cuba", flag: "🇨🇺" },
	{ code: "CVE", name: "Cape Verdean Escudo", country: "Cape Verde", flag: "🇨🇻" },
	{ code: "CZK", name: "Czech Koruna", country: "Czech Republic", flag: "🇨🇿" },
	{ code: "DJF", name: "Djiboutian Franc", country: "Djibouti", flag: "🇩🇯" },
	{ code: "DKK", name: "Danish Krone", country: "Denmark", flag: "🇩🇰" },
	{ code: "DOP", name: "Dominican Peso", country: "Dominican Republic", flag: "🇩🇴" },
	{ code: "DZD", name: "Algerian Dinar", country: "Algeria", flag: "🇩🇿" },
	{ code: "EGP", name: "Egyptian Pound", country: "Egypt", flag: "🇪🇬" },
	{ code: "ERN", name: "Eritrean Nakfa", country: "Eritrea", flag: "🇪🇷" },
	{ code: "ETB", name: "Ethiopian Birr", country: "Ethiopia", flag: "🇪🇹" },
	{ code: "EUR", name: "Euro", country: "European Union", flag: "🇪🇺" },
	{ code: "FJD", name: "Fijian Dollar", country: "Fiji", flag: "🇫🇯" },
	{ code: "FKP", name: "Falkland Islands Pound", country: "Falkland Islands", flag: "🇫🇰" },
	{ code: "GBP", name: "British Pound", country: "United Kingdom", flag: "🇬🇧" },
	{ code: "GEL", name: "Georgian Lari", country: "Georgia", flag: "🇬🇪" },
	{ code: "GHS", name: "Ghanaian Cedi", country: "Ghana", flag: "🇬🇭" },
	{ code: "GIP", name: "Gibraltar Pound", country: "Gibraltar", flag: "🇬🇮" },
	{ code: "GMD", name: "Gambian Dalasi", country: "Gambia", flag: "🇬🇲" },
	{ code: "GNF", name: "Guinean Franc", country: "Guinea", flag: "🇬🇳" },
	{ code: "GTQ", name: "Guatemalan Quetzal", country: "Guatemala", flag: "🇬🇹" },
	{ code: "GYD", name: "Guyanese Dollar", country: "Guyana", flag: "🇬🇾" },
	{ code: "HKD", name: "Hong Kong Dollar", country: "Hong Kong", flag: "🇭🇰" },
	{ code: "HNL", name: "Honduran Lempira", country: "Honduras", flag: "🇭🇳" },
	{ code: "HRK", name: "Croatian Kuna", country: "Croatia", flag: "🇭🇷" },
	{ code: "HTG", name: "Haitian Gourde", country: "Haiti", flag: "🇭🇹" },
	{ code: "HUF", name: "Hungarian Forint", country: "Hungary", flag: "🇭🇺" },
	{ code: "IDR", name: "Indonesian Rupiah", country: "Indonesia", flag: "🇮🇩" },
	{ code: "ILS", name: "Israeli New Shekel", country: "Israel", flag: "🇮🇱" },
	{ code: "INR", name: "Indian Rupee", country: "India", flag: "🇮🇳" },
	{ code: "IQD", name: "Iraqi Dinar", country: "Iraq", flag: "🇮🇶" },
	{ code: "IRR", name: "Iranian Rial", country: "Iran", flag: "🇮🇷" },
	{ code: "ISK", name: "Icelandic Króna", country: "Iceland", flag: "🇮🇸" },
	{ code: "JMD", name: "Jamaican Dollar", country: "Jamaica", flag: "🇯🇲" },
	{ code: "JOD", name: "Jordanian Dinar", country: "Jordan", flag: "🇯🇴" },
	{ code: "JPY", name: "Japanese Yen", country: "Japan", flag: "🇯🇵" },
	{ code: "KES", name: "Kenyan Shilling", country: "Kenya", flag: "🇰🇪" },
	{ code: "KGS", name: "Kyrgyzstani Som", country: "Kyrgyzstan", flag: "🇰🇬" },
	{ code: "KHR", name: "Cambodian Riel", country: "Cambodia", flag: "🇰🇭" },
	{ code: "KMF", name: "Comorian Franc", country: "Comoros", flag: "🇰🇲" },
	{ code: "KPW", name: "North Korean Won", country: "North Korea", flag: "🇰🇵" },
	{ code: "KRW", name: "South Korean Won", country: "South Korea", flag: "🇰🇷" },
	{ code: "KWD", name: "Kuwaiti Dinar", country: "Kuwait", flag: "🇰🇼" },
	{ code: "KYD", name: "Cayman Islands Dollar", country: "Cayman Islands", flag: "🇰🇾" },
	{ code: "KZT", name: "Kazakhstani Tenge", country: "Kazakhstan", flag: "🇰🇿" },
	{ code: "LAK", name: "Laotian Kip", country: "Laos", flag: "🇱🇦" },
	{ code: "LBP", name: "Lebanese Pound", country: "Lebanon", flag: "🇱🇧" },
	{ code: "LKR", name: "Sri Lankan Rupee", country: "Sri Lanka", flag: "🇱🇰" },
	{ code: "LRD", name: "Liberian Dollar", country: "Liberia", flag: "🇱🇷" },
	{ code: "LSL", name: "Lesotho Loti", country: "Lesotho", flag: "🇱🇸" },
	{ code: "LYD", name: "Libyan Dinar", country: "Libya", flag: "🇱🇾" },
	{ code: "MAD", name: "Moroccan Dirham", country: "Morocco", flag: "🇲🇦" },
	{ code: "MDL", name: "Moldovan Leu", country: "Moldova", flag: "🇲🇩" },
	{ code: "MGA", name: "Malagasy Ariary", country: "Madagascar", flag: "🇲🇬" },
	{ code: "MKD", name: "Macedonian Denar", country: "North Macedonia", flag: "🇲🇰" },
	{ code: "MMK", name: "Myanmar Kyat", country: "Myanmar", flag: "🇲🇲" },
	{ code: "MNT", name: "Mongolian Tögrög", country: "Mongolia", flag: "🇲🇳" },
	{ code: "MOP", name: "Macanese Pataca", country: "Macau", flag: "🇲🇴" },
	{ code: "MRU", name: "Mauritanian Ouguiya", country: "Mauritania", flag: "🇲🇷" },
	{ code: "MUR", name: "Mauritian Rupee", country: "Mauritius", flag: "🇲🇺" },
	{ code: "MVR", name: "Maldivian Rufiyaa", country: "Maldives", flag: "🇲🇻" },
	{ code: "MWK", name: "Malawian Kwacha", country: "Malawi", flag: "🇲🇼" },
	{ code: "MXN", name: "Mexican Peso", country: "Mexico", flag: "🇲🇽" },
	{ code: "MYR", name: "Malaysian Ringgit", country: "Malaysia", flag: "🇲🇾" },
	{ code: "MZN", name: "Mozambican Metical", country: "Mozambique", flag: "🇲🇿" },
	{ code: "NAD", name: "Namibian Dollar", country: "Namibia", flag: "🇳🇦" },
	{ code: "NGN", name: "Nigerian Naira", country: "Nigeria", flag: "🇳🇬" },
	{ code: "NIO", name: "Nicaraguan Córdoba", country: "Nicaragua", flag: "🇳🇮" },
	{ code: "NOK", name: "Norwegian Krone", country: "Norway", flag: "🇳🇴" },
	{ code: "NPR", name: "Nepalese Rupee", country: "Nepal", flag: "🇳🇵" },
	{ code: "NZD", name: "New Zealand Dollar", country: "New Zealand", flag: "🇳🇿" },
	{ code: "OMR", name: "Omani Rial", country: "Oman", flag: "🇴🇲" },
	{ code: "PAB", name: "Panamanian Balboa", country: "Panama", flag: "🇵🇦" },
	{ code: "PEN", name: "Peruvian Sol", country: "Peru", flag: "🇵🇪" },
	{ code: "PGK", name: "Papua New Guinean Kina", country: "Papua New Guinea", flag: "🇵🇬" },
	{ code: "PHP", name: "Philippine Peso", country: "Philippines", flag: "🇵🇭" },
	{ code: "PKR", name: "Pakistani Rupee", country: "Pakistan", flag: "🇵🇰" },
	{ code: "PLN", name: "Polish Złoty", country: "Poland", flag: "🇵🇱" },
	{ code: "PYG", name: "Paraguayan Guaraní", country: "Paraguay", flag: "🇵🇾" },
	{ code: "QAR", name: "Qatari Riyal", country: "Qatar", flag: "🇶🇦" },
	{ code: "RON", name: "Romanian Leu", country: "Romania", flag: "🇷🇴" },
	{ code: "RSD", name: "Serbian Dinar", country: "Serbia", flag: "🇷🇸" },
	{ code: "RUB", name: "Russian Ruble", country: "Russia", flag: "🇷🇺" },
	{ code: "RWF", name: "Rwandan Franc", country: "Rwanda", flag: "🇷🇼" },
	{ code: "SAR", name: "Saudi Riyal", country: "Saudi Arabia", flag: "🇸🇦" },
	{ code: "SBD", name: "Solomon Islands Dollar", country: "Solomon Islands", flag: "🇸🇧" },
	{ code: "SCR", name: "Seychellois Rupee", country: "Seychelles", flag: "🇸🇨" },
	{ code: "SDG", name: "Sudanese Pound", country: "Sudan", flag: "🇸🇩" },
	{ code: "SEK", name: "Swedish Krona", country: "Sweden", flag: "🇸🇪" },
	{ code: "SGD", name: "Singapore Dollar", country: "Singapore", flag: "🇸🇬" },
	{ code: "SHP", name: "Saint Helena Pound", country: "Saint Helena", flag: "🇸🇭" },
	{ code: "SLL", name: "Sierra Leonean Leone", country: "Sierra Leone", flag: "🇸🇱" },
	{ code: "SOS", name: "Somali Shilling", country: "Somalia", flag: "🇸🇴" },
	{ code: "SRD", name: "Surinamese Dollar", country: "Suriname", flag: "🇸🇷" },
	{ code: "STN", name: "São Tomé and Príncipe Dobra", country: "São Tomé and Príncipe", flag: "🇸🇹" },
	{ code: "SVC", name: "Salvadoran Colón", country: "El Salvador", flag: "🇸🇻" },
	{ code: "SYP", name: "Syrian Pound", country: "Syria", flag: "🇸🇾" },
	{ code: "SZL", name: "Swazi Lilangeni", country: "Eswatini", flag: "🇸🇿" },
	{ code: "THB", name: "Thai Baht", country: "Thailand", flag: "🇹🇭" },
	{ code: "TJS", name: "Tajikistani Somoni", country: "Tajikistan", flag: "🇹🇯" },
	{ code: "TMT", name: "Turkmenistan Manat", country: "Turkmenistan", flag: "🇹🇲" },
	{ code: "TND", name: "Tunisian Dinar", country: "Tunisia", flag: "🇹🇳" },
	{ code: "TOP", name: "Tongan Paʻanga", country: "Tonga", flag: "🇹🇴" },
	{ code: "TRY", name: "Turkish Lira", country: "Turkey", flag: "🇹🇷" },
	{ code: "TTD", name: "Trinidad and Tobago Dollar", country: "Trinidad and Tobago", flag: "🇹🇹" },
	{ code: "TWD", name: "New Taiwan Dollar", country: "Taiwan", flag: "🇹🇼" },
	{ code: "TZS", name: "Tanzanian Shilling", country: "Tanzania", flag: "🇹🇿" },
	{ code: "UAH", name: "Ukrainian Hryvnia", country: "Ukraine", flag: "🇺🇦" },
	{ code: "UGX", name: "Ugandan Shilling", country: "Uganda", flag: "🇺🇬" },
	{ code: "USD", name: "US Dollar", country: "United States", flag: "🇺🇸" },
	{ code: "UYU", name: "Uruguayan Peso", country: "Uruguay", flag: "🇺🇾" },
	{ code: "UZS", name: "Uzbekistani Som", country: "Uzbekistan", flag: "🇺🇿" },
	{ code: "VES", name: "Venezuelan Bolívar", country: "Venezuela", flag: "🇻🇪" },
	{ code: "VND", name: "Vietnamese Đồng", country: "Vietnam", flag: "🇻🇳" },
	{ code: "VUV", name: "Vanuatu Vatu", country: "Vanuatu", flag: "🇻🇺" },
	{ code: "WST", name: "Samoan Tālā", country: "Samoa", flag: "🇼🇸" },
	{ code: "XAF", name: "Central African CFA Franc", country: "Central Africa", flag: "🌍" },
	{ code: "XCD", name: "East Caribbean Dollar", country: "Eastern Caribbean", flag: "🌎" },
	{ code: "XOF", name: "West African CFA Franc", country: "West Africa", flag: "🌍" },
	{ code: "XPF", name: "CFP Franc", country: "French Polynesia", flag: "🇵🇫" },
	{ code: "YER", name: "Yemeni Rial", country: "Yemen", flag: "🇾🇪" },
	{ code: "ZAR", name: "South African Rand", country: "South Africa", flag: "🇿🇦" },
	{ code: "ZMW", name: "Zambian Kwacha", country: "Zambia", flag: "🇿🇲" },
	{ code: "ZWL", name: "Zimbabwean Dollar", country: "Zimbabwe", flag: "🇿🇼" },
];

/**
 * Case-insensitive search across code, name, and country.
 * Empty query returns all entries.
 */
export function searchCurrencies(query: string): CurrencyEntry[] {
	if (!query.trim()) return CURRENCIES;
	const q = query.toLowerCase();
	return CURRENCIES.filter(
		(c) =>
			c.code.toLowerCase().includes(q) ||
			c.name.toLowerCase().includes(q) ||
			c.country.toLowerCase().includes(q)
	);
}

/** Look up a single entry by ISO code (case-insensitive). */
export function getCurrencyByCode(code: string): CurrencyEntry | undefined {
	return CURRENCIES.find((c) => c.code.toLowerCase() === code.toLowerCase());
}
